listener 8883
protocol mqtt
allow_anonymous false
cafile /mosquitto/certs/ca.crt
certfile /mosquitto/certs/mosquitto.crt
keyfile /mosquitto/certs/mosquitto.key
require_certificate true
use_identity_as_username true
acl_file /mosquitto/config/acl.conf
persistence true
persistence_location /mosquitto/data/
log_dest stdout
log_type error
log_type warning
connection_messages false
max_queued_messages 100000
max_inflight_messages 1000
