'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),tls=require('node:tls'),{execFileSync}=require('node:child_process');
const {runFleet,makeEvent,snapshot,sleep}=require('./experiment.cjs');const {connect,publish}=require('../src/bus.cjs');
const root=path.resolve(__dirname,'..');const observations=[];const engine=process.env.CONTAINER_ENGINE||'podman';
async function check(name,fn){const start=Date.now();try{const evidence=await fn();observations.push({name,passed:true,durationMs:Date.now()-start,evidence});console.log('PASS '+name);}catch(e){observations.push({name,passed:false,durationMs:Date.now()-start,error:e.message});console.error('FAIL '+name+': '+e.message);throw e;}finally{fs.mkdirSync(path.join(root,'evidence'),{recursive:true});fs.writeFileSync(path.join(root,'evidence/functional-tests.json'),JSON.stringify({observedAt:new Date().toISOString(),tests:observations},null,2)+'\n');}}
async function main(){
 let core,flow;
 await check('main pipeline reaches all three control modes and both aggregation shards',async()=>{core=await runFleet({devices:4,zones:4,ticks:4,intervalMs:1000,scenario:'modes',label:'functional-main'});assert.equal(core.finalBacklog,0);assert.deepEqual(Object.keys(core.final.aggregators).sort(),['aggregator-a','aggregator-b']);const modes=Object.values(core.final.zones).map(z=>z.actuator.mode);assert.deepEqual([...new Set(modes)].sort(),['cool','idle','ventilate']);assert.equal(core.final.counts['sensor.reading'],16);assert.equal(core.final.counts['zone.metrics.updated'],16);return {runId:core.runId,modes,counts:core.final.counts,latency:core.final.latencyMs};});
 await check('independent Node-RED MQTT pipeline matches main control outputs',async()=>{flow=await runFleet({devices:4,zones:4,ticks:4,intervalMs:1000,scenario:'modes',pipeline:'flow',label:'functional-flow'});assert.equal(flow.finalBacklog,0);for(const [z,v]of Object.entries(core.final.zones)){assert.equal(flow.final.zones[z].actuator.mode,v.actuator.mode);assert.equal(flow.final.zones[z].actuator.fanSpeed,v.actuator.fanSpeed);assert.equal(flow.final.zones[z].metrics.averageTemperatureC,v.metrics.averageTemperatureC);}const api=await(await fetch('http://localhost:3180/api/status')).json();assert.equal(api.broker.connected,true);return {runId:flow.runId,counts:flow.final.counts,nodeRedCounts:api.counts};});
 await check('duplicate MQTT deliveries do not duplicate logical outputs',async()=>{const r=await runFleet({devices:4,ticks:3,intervalMs:1000,duplicate:true,label:'duplicates'});for(const type of ['device.telemetry.raw','sensor.reading','zone.metrics.updated','actuator.command.created','actuator.command.applied'])assert.equal(r.final.counts[type],12);return {runId:r.runId,publishes:r.mqttPublishes,unique:r.uniqueRawOffered,counts:r.final.counts};});
 await check('gateway rejects bad sensor data and topic identity mismatch',async()=>{const runId='invalid-'+Date.now();const c=await connect('sensor-0001');const edits=[p=>{p.temperatureC=81;},p=>{p.humidityPercent=101;},p=>{p.occupancyCount=-1;},p=>{p.co2Ppm=399;},p=>{p.batteryPercent=-1;},p=>{delete p.zoneId;},p=>{p.deviceId='sensor-0002';}];try{for(let i=0;i<edits.length;i++){const e=makeEvent(runId,0,i);edits[i](e.payload);await c.publishAsync(`hvac/main/${runId}/raw/sensor-0001`,JSON.stringify(e),{qos:1});}}finally{await c.endAsync();}let s;for(let i=0;i<40;i++){s=await snapshot(runId);if(s.counts['gateway.telemetry.rejected']===7)break;await sleep(250);}assert.equal(s.counts['gateway.telemetry.rejected'],7);assert.equal(s.counts['sensor.reading']||0,0);assert.equal(s.counts['actuator.command.applied']||0,0);return {runId,counts:s.counts};});
 await check('MQTT mutual TLS rejects a client without a certificate',async()=>{return await new Promise((resolve,reject)=>{const socket=tls.connect({host:'127.0.0.1',port:8883,servername:'localhost',ca:fs.readFileSync(path.join(root,'.private/certs/ca.crt')),rejectUnauthorized:true});const timer=setTimeout(()=>{socket.destroy();reject(Error('No rejection observed'));},5000);socket.on('error',e=>{clearTimeout(timer);resolve({rejected:true,code:e.code,message:e.message.split('\n')[0]});});socket.on('close',()=>clearTimeout(timer));});});
 await check('certificate-bound ACL denies another device topic',async()=>{const c=await connect('sensor-0001');let rejected=false,reason;try{await c.publishAsync(`hvac/main/acl-${Date.now()}/raw/sensor-0002`,JSON.stringify(makeEvent('acl',1,0)),{qos:1});}catch(e){rejected=true;reason=e.message;}finally{await c.endAsync();}assert.equal(rejected,true);return {rejected,reason};});
 await check('CEP detects sustained high CO2 and subsequent silence',async()=>{const r=await runFleet({devices:1,zones:1,ticks:12,intervalMs:1000,scenario:'co2',label:'cep'});await sleep(6000);const s=await snapshot(r.runId);assert.ok(s.alerts.some(a=>a.kind==='sustained_co2'));assert.ok(s.alerts.some(a=>a.kind==='silent_device'));return {runId:r.runId,alerts:s.alerts};});
 await check('controller restart drains persistent MQTT backlog without missing commands',async()=>{let stoppedAt,restartedAt;const r=await runFleet({devices:4,ticks:10,intervalMs:1000,label:'restart',onTick:async tick=>{if(tick===2){execFileSync(engine,['stop','--time','2','sit314-hvac-controller']);stoppedAt=Date.now();}if(tick===5){execFileSync(engine,['start','sit314-hvac-controller']);restartedAt=Date.now();}}});assert.equal(r.finalBacklog,0);assert.equal(r.final.counts['actuator.command.created'],40);return {runId:r.runId,stoppedAt,restartedAt,counts:r.final.counts,latency:r.final.latencyMs,normalLatencySLAExcludedDuringInjectedOutage:true};});
 await check('storage restart preserves accepted event and rollup state',async()=>{const before=await snapshot(core.runId);execFileSync(engine,['restart','--time','5','sit314-hvac-storage']);let after;for(let i=0;i<50;i++){try{after=await snapshot(core.runId);break;}catch{await sleep(200);}}assert.ok(after);assert.deepEqual(after.counts,before.counts);assert.deepEqual(after.rollups,before.rollups);return {runId:core.runId,counts:after.counts,rollups:after.rollups.length};});
 await check('local control operates with no container WAN egress',async()=>{let result;try{result=execFileSync(engine,['exec','sit314-hvac-gateway','node','-e',"const h=require('https');const r=h.get('https://example.com',()=>process.exit(9));r.setTimeout(2000,()=>r.destroy(new Error('timeout')));r.on('error',e=>{console.log(e.code||e.message);process.exit(0)});"],{encoding:'utf8',timeout:6000}).trim();}catch(e){throw Error('WAN isolation probe did not return expected blocked result: '+e.message);}const r=await runFleet({devices:4,ticks:3,intervalMs:1000,label:'offline'});assert.equal(r.finalBacklog,0);return {network:'internal-only',externalProbe:result,runId:r.runId,counts:r.final.counts};});
 console.log('FUNCTIONAL_TESTS_COMPLETE '+observations.length);
}
main().catch(e=>{console.error(e);process.exitCode=1;});
